name: PR Checks

on: [pull_request]

jobs:

  run_pr_check:
    name: Running PR Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
            
      - name: Install Dependencies
        run: npm install

      - name: Run a one-line script
        run: echo Hello, world!